add Create project
tuannd995/zinza-training pull request #14
Opened 2021-09-30 09:42 UTC by duyhiep2519

2021-09-30 10:12 UTC, tuannd995 requested changes

2021-09-30 10:12 UTC, tuannd995 commented on src/components/CreateProject/AddMember.tsx
> +}: AddMemberProps) {
E xem lại cách đặt tên nhé (AddMember là hành động, k phải tên 1 component, có thể dùng tên khác kiểu như `ProjectMemberSwitcher`): 

Props ở đây chỉ cần 2 cái:
- allUsers: danh sách tất cả các users
- onChange(users: User[]) => void. Hành động khi list user của project được update
- value: User[]. Danh sách users được chọn vào thành members (ô bên phải). Ô bên trái sẽ là allUsers - đã chọn

Ngoài ra xem lại định nghĩa màn hình:

```
-  Trái: Select multiple, chọn và click vào mũi tên sang phải thì add vào list bên phải (member của dự án)
- Phải: tương tự ô bên trái 
```

=> phải ấn vào nút mũi tên (trái - phải) thì mới add/remove trong 2 list. Và có thể select nhiều xong mới click để chuyển các cái đã chọn

2021-09-30 10:12 UTC, tuannd995 commented on src/components/CreateProject/index.tsx
> +
như comment ở trên. allUsers là tất cả các member (chỉ là Member - k phải cả PM với Admin)

```suggestion
   const allMemberUsers = useMemo(() => {
         return USERS.filter(...........)
   }, [])

```

2021-09-30 10:12 UTC, tuannd995 commented on src/components/CreateProject/index.tsx
> +   });
Tạo type riêng để create Project nhé

```suggestion
   const [formData, setFormData] = useState<ProjectFormData>({
      id: 1,
      name: '',
      description: '',
      client: '',
      status: ProjectStatus.Pending,
      members: [],
      pm: null
   });
```

2021-09-30 10:12 UTC, tuannd995 commented on src/components/CreateProject/index.tsx
> +               <button type="submit">Create</button>
disable button Create khi form lỗi nhé (chưa điền các field required)

2021-09-30 10:12 UTC, tuannd995 commented on src/components/CreateProject/useCreateProjectForm.ts
> +      onSubmit: onLogin,
Update validate với cả view nữa:
- PM required
- Description, StartDate, EndDate có thể trống

2021-09-30 10:12 UTC, tuannd995 commented on src/components/ListProjects/index.tsx
> +               { name: 'List Projects', link: '/projects' },
Đổi luôn tên Thành Projects

2021-09-30 10:12 UTC, tuannd995 commented on src/components/Users/index.tsx
> +   console.log(listUsers, pagination.page);
remove log

2021-10-01 04:04 UTC, tuannd995 requested changes

2021-10-01 04:04 UTC, tuannd995 commented on src/components/CreateProject/index.tsx
> +                  <label>StartDate*</label>
k required trường này và `endDate` nhé. Ngoài ra e có thể thêm class `required` cho label và css add * vào `after` content

2021-10-01 04:04 UTC, tuannd995 commented on src/components/CreateProject/index.tsx
> +               <button disabled={!values.name || !values.client} type="submit">
required thêm trường PM và status nữa nhé

2021-10-01 04:04 UTC, tuannd995 commented on src/components/CreateProject/useCreateProjectForm.ts
> +      onSubmit: onLogin,
còn PM required. Thêm required cái status nữa

2021-10-01 04:09 UTC, tuannd995 requested changes

2021-10-01 04:09 UTC, tuannd995 commented on src/components/CreateProject/ProjectMemberSwitcher.tsx
> +   function handleRemoveUserFromArry<T>(item: T, array: T[]): void {
tránh Gerenic type ở đây nhé, vì mình biết rõ nó là loại User, chỉ dùng khi param truyền vào linh động type (có thể nhận nhiều type khác nhau

2021-10-01 04:17 UTC, duyhiep2519 commented on src/components/CreateProject/ProjectMemberSwitcher.tsx
> +   function handleRemoveUserFromArry<T>(item: T, array: T[]): void {
tại cái này em dùng để remove cả cái listUserSelected mà cái ý thì em lại lưu id của user

2021-10-01 04:18 UTC, tuannd995 commented on src/components/CreateProject/ProjectMemberSwitcher.tsx
> +   function handleRemoveUserFromArry<T>(item: T, array: T[]): void {
ok e

2021-10-01 06:24 UTC, tuannd995 approved these changes

2021-10-01 06:46 UTC, merged