add drag and drop
tuannd995/zinza-training pull request #18
Opened 2021-10-05 10:29 UTC by duyhiep2519

2021-10-05 10:47 UTC, tuannd995 requested changes
Chú ý tên nhánh nhé :D. Vì nó là con 1 nhánh khác nên e có thể để kiểu `feature/project_detail_task/test_drag_drop`

2021-10-05 10:47 UTC, tuannd995 commented on src/components/ProjectDetail/ProjectTasks.tsx
> +      listTasks = { ...newListTasks };
```suggestion
      setTasksMap(newListTasks);
```

2021-10-05 10:47 UTC, tuannd995 commented on src/components/ProjectDetail/ProjectTasks.tsx
> +}
```suggestion
interface TasksMap {
   [key: string]: Task[];
}
```

2021-10-05 10:47 UTC, tuannd995 commented on src/components/ProjectDetail/ProjectTasks.tsx
> +   }, [projectId]);
```suggestion
   const [tasksMap, setTasksMap] = useState<TasksMap>({})
   useEffect(() => {
      let lists: TasksMap = {};
      const tasks = TASKS.filter((task) => task.projectId === projectId);
      lists[TaskStatus.Requesting] = tasks.filter(
         (task) => task.status === TaskStatus.Requesting
      );
      lists[TaskStatus.Unscheduled] = tasks.filter(
         (task) => task.status === TaskStatus.Unscheduled
      );
      lists[TaskStatus.Doing] = tasks.filter(
         (task) => task.status === TaskStatus.Doing
      );
      lists[TaskStatus.Reviewing] = tasks.filter(
         (task) => task.status === TaskStatus.Reviewing
      );
      lists[TaskStatus.Completed] = tasks.filter(
         (task) => task.status === TaskStatus.Completed
      );
      setTasksMap(lists);
   }, []);
```

listTasks ở đây có thể thay đổi nên e dùng useState nhé, useMemo dùng để tính toán 1 biến dựa trên các biến khác, k được thay đổi nó kiểu gán mới

2021-10-05 10:50 UTC, tuannd995 requested changes

2021-10-05 10:50 UTC, tuannd995 commented on src/components/ProjectDetail/ProjectTasks.tsx
>  function ProjectTasks({ projectId }: TasksProps) {
E chuyển các đoạn code đằng sau ra 1 component riêng truyền vào danh sách task nhé, ở component này mình sẽ lấy data và truyền vào nó. `<TaskListBoard tasks={tasks}>`

2021-10-05 10:51 UTC, duyhiep2519 commented
> Chú ý tên nhánh nhé :D. Vì nó là con 1 nhánh khác nên e có thể để kiểu `feature/project_detail_task/test_drag_drop`

Vâng anh, em sẽ chú ý 😁

2021-10-05 13:54 UTC, duyhiep2519 commented on src/components/ProjectDetail/ProjectTasks.tsx
>  function ProjectTasks({ projectId }: TasksProps) {
Em có sửa lại rồi ạ, anh review giúp em xem đã được chưa ạ

2021-10-06 01:52 UTC, tuannd995 approved these changes

2021-10-06 01:52 UTC, merged