Feature/login api
tuannd995/zinza-training pull request #28
Opened 2021-10-20 07:35 UTC by duyhiep2519

![image](https://user-images.githubusercontent.com/48683793/138048001-04bc4b56-2ff9-4cfb-9d2c-dd2fc9233807.png)
Ở file Router.tsx em có phần lấy **currentUser** từ redux, mà lần đầu render cái **currentUser** của em nó là **{}** xong nó mới get User từ api rồi lấy được ra ở lần sau, nhưng mà em không làm sao để cho cái Router nó check lại để chuyển sang trang Home cho em

2021-10-20 10:16 UTC, tuannd995 commented
Hook e có thể trả về useCallback async được mà. A k hiểu lắm, e có thể push code hiện tại lên a xem dc k

2021-10-20 10:59 UTC, tuannd995 commented on src/components/Login/index.tsx
> +         window.location.reload();
để cái này ra hook hoặc function nhá

2021-10-20 10:59 UTC, tuannd995 commented on src/hooks/useApi.ts
> +   baseURL: 'http://localhost:5000/',
để trong env

2021-10-20 11:17 UTC, tuannd995 requested changes

2021-10-20 11:17 UTC, tuannd995 commented on src/features/user/userSlice.ts
> +      const response = await userApi.getInfo();
lưu luôn storage ở đây thử xem có được k e

2021-10-20 13:30 UTC, hungnp194 commented on src/hooks/useApi.ts
> +};
A có 1 số góp ý nhỏ.
- fetchData() nên cho vào useMemo
- **url** / **method** / **body** nên cho vào dependencies
- Nên fetchData mỗi lần dependencies thay đổi. Body là object vì vậy mình có thể tạo 1 state với init value là body. Mỗi lần body đổi thì dùng [isEqual](https://lodash.com/docs/4.17.15#isEqual) của lodash để compare xem giá trị có thực sự thay đổi không và setState mới

2021-10-20 16:13 UTC, duyhiep2519 commented on src/hooks/useApi.ts
> +};
Vâng, em viết được rồi ạ

2021-10-21 02:57 UTC, tuannd995 reviewed
- E update lại `useForm` hook, không gọi onSubmit trong useEffect (nó bị gọi 2 lần). hãy gọi nó trong handleSubmit, khi check không có lỗi
- Update dependencies của useForm (onsubmit có thể là hàm promise)

2021-10-21 02:57 UTC, tuannd995 commented on src/utils/auth.ts
> +         JSON.stringify(Object.values(response['accessToken'])[0])
```suggestion
         response['accessToken']
```

2021-10-21 02:57 UTC, tuannd995 commented on src/utils/auth.ts
> -   window.localStorage.removeItem('user');
xóa user khi login & cho các key localStorage vào const

2021-10-21 02:57 UTC, tuannd995 commented on src/routeConfig/Route.tsx
>  interface Props extends RouteProps {
Khi vào login mà đã login rồi thì redirect sang homepage

2021-10-21 02:57 UTC, tuannd995 commented on src/components/Login/index.tsx
>        }
```suggestion
      const success = await login(username, password);
      if (success) {
         resetForm();
         history.push('/');
      } else {
         alert('login info is incorrect!');
      }
```

2021-10-21 02:57 UTC, tuannd995 commented on src/components/Login/index.tsx
> +   const dispatch = useAppDispatch();
```suggestion
   const { login, loading } = useLogin();
```

Khi loading = true thì hiển thị overlay loading trên màn hình nhé
![image](https://user-images.githubusercontent.com/31428578/138203027-bc703cd2-67b3-4c53-a187-51df0d3415c8.png)

2021-10-21 02:57 UTC, tuannd995 commented on src/hooks/useApi.ts
> +const useApi = ({ url, method, body, callable }: UseApiProps) => {
hook này a k thấy sử dụng ở đâu cả, và bị lặp code với axiosClient

2021-10-21 02:57 UTC, tuannd995 commented on src/api/axiosClient.ts
> +      )}`,
Set header bằng interceptors nhé, và không cần Json parse vì nó vốn là string rồi

```
axiosClient.interceptors.request.use(
   config => {
      const token = localStorage.getItem(STORAGE_KEY.token);
      if (token) {
         config.headers.Authorization = `Bearer ` + token;
      }
      return config;
   },
   error => Promise.reject(error)
);
```

2021-10-21 05:48 UTC, duyhiep2519 commented
> * E update lại `useForm` hook, không gọi onSubmit trong useEffect (nó bị gọi 2 lần). hãy gọi nó trong handleSubmit, khi check không có lỗi
> * Update dependencies của useForm (onsubmit có thể là hàm promise)
> 
> ```
> 
> type CallbackFunc = () => void
> type PromiseFunc = () => Promise<void>
> 
> interface Dependencies {
>    onSubmit: CallbackFunc | PromiseFunc;
>    fields: Field[];
> }
> ```
> 
> * hàm `validateValue` compareValidate có fix cứng field password, e có thể update lại sao cho n linh động (có thể truyền tên field vào)

Anh ơi, nếu em để onSubmit vào handleSubmit thì em phải ấn 2 lần button để đợi nó validate xong mới gọi đc onSubmit ạ

2021-10-21 05:49 UTC, tuannd995 commented
A đã test thử, đâu cần ấn 2 lần đâu?

2021-10-21 05:51 UTC, duyhiep2519 commented
> A đã test thử, đâu cần ấn 2 lần đâu?

Anh test code em push lên thử xem ạ, ở máy em em sửa xong phải ấn 2 lần

2021-10-21 06:01 UTC, tuannd995 commented on src/hooks/useForm.ts
>     };
cái này làm đơn giản thôi e, `isSubmit` ở đây đâu cần thiết đâu nhỉ, state này thừa nên e bị lỗi phải click 2 lần đấy
```suggestion
   const handleSubmit = (event) => {
      event.preventDefault();
      setErrors(validateValue(values, fields));
      if (Object.keys(errors).length === 0) {
         onSubmit();
      }
   };
```

2021-10-21 06:16 UTC, tuannd995 commented on .env
> +REACT_APP_BASEURL=http://localhost:5000/
ignore .env file đi nhé

2021-10-21 07:45 UTC, tuannd995 commented on src/hooks/useApi.ts
> +export const useApi = ({ url, method, body }: UseApiProps) => {
Thực ra k cần hook này lắm, viết kiểu service sẽ dễ hiểu hơn. A có đẩy phần a code thử lên nhánh khác. Nếu e tìm hiểu lâu quá thì có thể tham khảo của a (tạo PR vào nhánh này để nhìn dễ hơn `hotfix_feature/login_api`)

2021-10-21 07:54 UTC, duyhiep2519 commented on src/hooks/useApi.ts
> +export const useApi = ({ url, method, body }: UseApiProps) => {
Vâng, ra là cái hook là của riêng Login ạ, em làm nãy h 1 cái hook chung để xử lý response của cái useApi .
 Viết sevices như kia em lại quen 😁

2021-10-21 10:50 UTC, tuannd995 requested changes
Sửa nốt nhé

2021-10-21 10:50 UTC, tuannd995 commented on src/components/Login/index.tsx
> +   }
E chưa sửa chỗ này. Nếu error thì show 1 cái alert message dưới `Login to Dashboard` header (Thông tin đăng nhập k đúng)

![image](https://user-images.githubusercontent.com/31428578/138263136-7f615a15-f557-47f4-ab67-ee6b3def1f72.png)

2021-10-22 03:16 UTC, tuannd995 approved these changes

2021-10-22 03:20 UTC, merged